# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	# Add an array element for each project
	projects = []

	# The most common configuration options are documented and commented below.
	# For a complete reference, please see the online documentation at
	# https://docs.vagrantup.com.

	# Every Vagrant development environment requires a box. You can search for
	# boxes at https://atlas.hashicorp.com/search.
	config.vm.box = "centos/7"

	# Create a forwarded port mapping which allows access to a specific port
	# within the machine from a port on the host machine.

	# Allow to access MariaDB on port 33060
	config.vm.network "forwarded_port", guest: 3306, host: 33067

	# Assign a port for HTTP access
	config.vm.network "forwarded_port", guest: 80, host: 8807

	# Assign a port for HTTPS access
	config.vm.network "forwarded_port", guest: 443, host: 8447

	# Share an additional folder to the guest VM. The first argument is
	# the path on the host to the actual folder. The second argument is
	# the path on the guest to mount the folder. And the optional third
	# argument is a set of non-required options.

	# Disable default syncing folder to avoid syncing all projects.
	config.vm.synced_folder ".", "/vagrant", disabled: true

	# Enable provisioning with a shell script. Additional provisioners such as
	# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	# documentation for more information about their specific syntax and use.
	config.vm.provision "shell", path: "~/Documents/server/vagrant-setup/centos-7-php-7-1-apache-latest-http-2-mariadb/vm-bootstrap.sh"

	# Share any additional folder here
	# config.vm.synced_folder "~/Documents/web-projects/domain.com", "/var/www/vhosts/domain.com"

	projects.each do |project|
		# Shares a folder for each project
		config.vm.synced_folder "~/Documents/web-projects/php-7-1-http-2/"+project, "/var/www/vhosts/"+project

		# Creates Apache configuration files and SSL config if N/A
		config.vm.provision "shell", path: '~/Documents/server/vagrant-setup/centos-7-php-7-1-apache-latest-http-2-mariadb/apache-and-ssl-config.sh', run: "always" do |s|
			s.args = [project]
		end
	end

	# Restart Apache
	config.vm.provision "shell", inline: 'systemctl restart httpd.service', run: "always"
end
